# Generated by Django 4.1.12 on 2023-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
